testthat::test_that("les modèles survey sont finis et respectent leurs populations", {
  requireNamespace("survey",quietly=TRUE)
  m <- readRDS("../../outputs/models/modeles_statistiques.rds")
  a <- readRDS("../../data/processed/base_analytique.rds")
  testthat::expect_true(all(c("mod_dif_1","mod_dif_2","mod_dif_final","mod_eva_final","mod_num_final","mod_gap_final","mod_profil_final") %in% names(m)))
  for(n in names(m)) {
    z <- m[[n]]
    testthat::expect_s3_class(z,"svyglm")
    testthat::expect_true(z$converged)
    testthat::expect_true(all(is.finite(coef(z))) && all(is.finite(vcov(z))))
    testthat::expect_equal(nrow(z$model),length(z$ids_analyse))
    testthat::expect_equal(anyDuplicated(z$ids_analyse),0L)
    testthat::expect_true(all(z$ids_analyse %in% a$id_enseignant))
    testthat::expect_true(all.vars(formula(z))[1] %in% c(names(a),"profil_2"))
    testthat::expect_equal(z$rank,length(coef(z)))
    testthat::expect_true(all(is.finite(fitted(z))))
  }
  testthat::expect_identical(m$mod_dif_1$ids_analyse,m$mod_dif_final$ids_analyse)
  testthat::expect_identical(m$mod_eva_1$ids_analyse,m$mod_eva_final$ids_analyse)
  testthat::expect_true(all(fitted(m$mod_profil_final)>0 & fitted(m$mod_profil_final)<1))
  tab <- read.csv("../../outputs/tables/modeles_finaux.csv")
  testthat::expect_true(all(tab$ic95_inf<=tab$coefficient & tab$coefficient<=tab$ic95_sup))
  testthat::expect_true(all(tab$erreur_standard>0 & tab$p_value>=0 & tab$p_value<=1))
  diag <- read.csv("../../outputs/tables/diagnostic_modeles.csv")
  # Une extrapolation hors échelle est un diagnostic, jamais un écrêtage silencieux.
  testthat::expect_true(all(is.finite(diag$prediction_min)) & all(diag$prediction_min<diag$prediction_max))
  testthat::expect_true(all(diag$nb_predictions_hors_echelle>=0))
})

testthat::test_that("les prédictions et variantes ont des dénominateurs explicites", {
  p <- read.csv("../../outputs/tables/predicted_probabilities_profiles.csv")
  testthat::expect_equal(nrow(p),6L)
  testthat::expect_true(all(p$probabilite_profil_2>0 & p$probabilite_profil_2<1))
  testthat::expect_equal(p$probabilite_profil_1+p$probabilite_profil_2,rep(1,nrow(p)))
  testthat::expect_true(all(p$ic95_inf>=0 & p$ic95_inf<=p$probabilite_profil_2 & p$ic95_sup>=p$probabilite_profil_2 & p$ic95_sup<=1))
  testthat::expect_true(all(p$n_support_configuration>0))
  s <- read.csv("../../outputs/tables/sensibilite_modeles.csv")
  testthat::expect_equal(length(unique(s$scenario)),4L)
  testthat::expect_true(all(is.finite(s$coefficient)))
  testthat::expect_true(all(s$conclusion %in% c("ROBUSTE","MODEREMENT_ROBUSTE","SENSIBLE")))
  t <- read.csv("../../outputs/tables/bivariate_scores.csv")
  testthat::expect_true(nrow(t)>0 && all(t$n>0))
})

testthat::test_that("le catalogue et les sorties Quarto concordent avec les fichiers", {
  t <- read.csv("../../outputs/tables/catalogue_indicateurs.csv")
  testthat::expect_equal(nrow(t),35L)
  testthat::expect_equal(anyDuplicated(t$code_indicateur),0L)
  testthat::expect_true(all(c("definition","numerateur","denominateur","population","ponderation","source","statut_validation") %in% names(t)))
  testthat::expect_equal(t$valeur[t$code_indicateur=="TAUX_REPONSE"],1521/2000)
  r <- readRDS("../../outputs/models/resultats_quarto.rds")
  testthat::expect_equal(r$catalogue$code_indicateur,t$code_indicateur)
  fichiers <- paste0("../../",r$manifeste$fichier)
  testthat::expect_true(all(file.exists(fichiers)))
  testthat::expect_identical(unname(tools::md5sum(fichiers)),r$manifeste$md5)
})
