# Contrats de la livraison et cohérence des diagnostics ; pas d'exigence de collecte parfaite.
source("../../R/functions/quality.R",encoding="UTF-8",local=TRUE)
source("../../R/functions/dashboard_quality.R",encoding="UTF-8",local=TRUE)
qt_config <- yaml::read_yaml("../../config/config.yml")
qt_lire <- function(p) readRDS(file.path("../..",p))
qt_base <- qt_lire(qt_config$questionnaire_brut$sortie)
qt_echantillon <- qt_lire(qt_config$echantillon$sortie)
qt_dict <- read.csv("../../metadata/dictionnaire_variables.csv",fileEncoding="UTF-8")
qt_ordre <- read.csv("../../questionnaire/ordre_passation.csv",fileEncoding="UTF-8")
testthat::test_that("les contrats techniques et contextuels de la livraison sont respectés", {
  attendus <- c(names(qt_echantillon),qt_dict$variable,"repondant","statut_questionnaire","duree_secondes","date_reponse_simulee","taux_completion")
  testthat::expect_true(all(attendus %in% names(qt_base)))
  testthat::expect_false(any(is.na(qt_base$id_enseignant) | trimws(qt_base$id_enseignant)==""))
  ordinaux <- as.matrix(qt_base[setdiff(qt_dict$variable,"CTRL03")])
  testthat::expect_true(all(is.na(ordinaux)|ordinaux %in% 1:5))
  testthat::expect_true(all(is.na(qt_base$CTRL03)|qt_base$CTRL03 %in% 0:1))
  testthat::expect_true(all(is.finite(qt_base$poids_base)&qt_base$poids_base>0))
  testthat::expect_equal(qt_base$poids_base,qt_echantillon$poids_base[match(qt_base$id_enseignant,qt_echantillon$id_enseignant)])
  testthat::expect_equal(qt_base$poids_base,qt_base$N_h/qt_base$n_h)
  testthat::expect_true(all(is.finite(qt_base$taux_completion)&qt_base$taux_completion>=0&qt_base$taux_completion<=1))
  testthat::expect_true(all(is.finite(qt_base$duree_secondes)&qt_base$duree_secondes>=0))
  testthat::expect_true(all(qt_base$discipline[qt_base$degre=="Premier degré"]=="Polyvalent premier degré"))
  testthat::expect_true(all(qt_base$discipline[qt_base$degre=="Collège"]!="Polyvalent premier degré"))
  testthat::expect_true(all(qt_base$education_prioritaire[qt_base$secteur=="Privé sous contrat"]=="Hors EP"))
})
testthat::test_that("les anomalies métier sont détectées et les tableaux se réconcilient", {
  audit <- auditer_qualite(qt_base,qt_echantillon,qt_lire(qt_config$non_reponse$sortie_complete),
    qt_lire(qt_config$population$sortie),qt_dict,qt_ordre,
    read.csv("../../metadata/plan_controles.csv",fileEncoding="UTF-8"))
  z <- construire_dashboard_qualite(qt_base,qt_echantillon,qt_dict,qt_ordre,audit)
  db <- z$dashboard_qualite
  testthat::expect_gt(db$nb_reponses_rapides,0)
  testthat::expect_gt(db$nb_straightlining,0)
  testthat::expect_gt(db$taux_missing_global,0)
  testthat::expect_true(all(audit$synthese$resultat[audit$synthese$niveau_gravite=="CRITIQUE"]=="OK"))
  testthat::expect_equal(sum(z$missing_par_bloc$nb_manquants),sum(z$missing_par_repondant$nb_items_manquants))
  testthat::expect_equal(db$nb_questionnaires_complets+db$nb_partiels+db$nb_abandons,db$nb_lignes)
  testthat::expect_equal(db$taux_reponse,db$nb_repondants/db$nb_selectionnes)
  testthat::expect_equal(db$nb_valeurs_hors_bornes,0)
})
