testthat::test_that("la classification trace ses cas et ses solutions", {
  a <- readRDS("../../data/processed/base_analytique.rds")
  b <- readRDS("../../data/processed/base_analytique_profils.rds")
  s <- read.csv("../../outputs/tables/selection_clustering.csv")
  z <- grep("^Z_",names(a),value=TRUE)
  testthat::expect_identical(a$id_enseignant,b$id_enseignant)
  testthat::expect_true(all(vapply(names(a),function(n)identical(a[[n]],b[[n]]),logical(1))))
  testthat::expect_identical(s$inclus_clustering,unname(complete.cases(a[z])))
  testthat::expect_identical(is.na(b$profil_pratiques),!s$inclus_clustering)
  c <- read.csv("../../outputs/tables/comparaison_clusters.csv")
  testthat::expect_setequal(c$k,2:6)
  testthat::expect_true(all(c$taille_min>0 & c$taille_max<=sum(s$inclus_clustering)))
  testthat::expect_true(all(c$silhouette_moyenne>=-1 & c$silhouette_moyenne<=1))
  testthat::expect_true(all(diff(c$inertie_intra)<0))
  r <- read.csv("../../outputs/tables/robustesse_clusters.csv")
  testthat::expect_true(all(r$ARI>=-1 & r$ARI<=1))
  p <- read.csv("../../outputs/tables/profils_scores.csv")
  testthat::expect_equal(nrow(p),2*8*4)
  testthat::expect_true(all(p$n>0 & is.finite(p$moyenne_ponderee)))
  tailles <- table(b$profil_pratiques)
  testthat::expect_equal(p$n+p$n_manquants,as.numeric(tailles[p$profil_pratiques]))
  v <- read.csv("../../outputs/tables/acp_variance.csv")
  testthat::expect_equal(sum(v$proportion),1)
})

testthat::test_that("les profils finaux et les algorithmes sont reproductibles", {
  a <- readRDS("../../data/processed/base_analytique.rds")
  r <- readRDS("../../outputs/models/comparaison_clustering.rds")
  cfg <- yaml::read_yaml("../../config/clustering.yml")
  k <- yaml::read_yaml("../../metadata/decision_clustering.yml")$k_retenu
  inclus <- r$selection$inclus_clustering
  testthat::expect_false(anyNA(a$CLUSTER_ID[inclus]))
  testthat::expect_true(all(is.na(a$CLUSTER_ID[!inclus])))
  testthat::expect_setequal(unique(a$CLUSTER_ID[inclus]),seq_len(k))
  # 5 % : alerte de précision descriptive, jamais une preuve de validité des classes.
  testthat::expect_true(min(table(a$CLUSTER_ID))>=.05*sum(inclus))
  testthat::expect_equal(anyDuplicated(a$id_enseignant),0L)
  testthat::expect_identical(unname(cutree(hclust(dist(r$x),method="ward.D2"),k)),a$CLUSTER_ID[inclus])
  set.seed(cfg$graine+1L)
  km <- kmeans(r$x,centers=k,nstart=cfg$kmeans_nstart,iter.max=100)
  testthat::expect_identical(km$cluster,readRDS("../../outputs/models/kmeans_scores.rds")$cluster)
  set.seed(cfg$graine)
  i <- sort(sample.int(nrow(r$x),floor(cfg$fraction_sous_echantillon*nrow(r$x))))
  source("../../R/functions/clustering.R")
  ari <- rand_ajuste(r$solutions[[as.character(k)]][i],cutree(hclust(dist(r$x[i,]),method="ward.D2"),k))
  tab <- read.csv("../../outputs/tables/stabilite_clusters.csv")
  testthat::expect_equal(ari,tab$ARI[tab$k==k & tab$repetition==1])
  c <- read.csv("../../outputs/tables/composition_profils.csv")
  sommes <- aggregate(pourcentage_pondere~profil+variable,c,sum)
  testthat::expect_true(all(abs(sommes$pourcentage_pondere-100)<1e-8))
  gaps <- read.csv("../../outputs/tables/gap_par_profil.csv")
  testthat::expect_equal(gaps$moyenne_ponderee,gaps$priorite_moyenne_appariee-gaps$pratique_moyenne_appariee)
  testthat::expect_true(all(gaps$part_priorite_4_5_et_gap_positif>=0 & gaps$part_priorite_4_5_et_gap_positif<=1))
})

testthat::test_that("l'ARI ne dépend pas des noms des classes", {
  source("../../R/functions/clustering.R")
  testthat::expect_equal(rand_ajuste(c(1,1,2,2),c(8,8,3,3)),1)
  testthat::expect_equal(rand_ajuste(c(1,1,2,2),c(1,2,1,2)),-.5)
})
