testthat::test_that("le diagnostic psychométrique respecte les données observées", {
  b <- readRDS("../../data/processed/questionnaire_clean.rds")
  x <- read.csv("../../outputs/tables/diagnostic_items_psychometrie.csv",fileEncoding="UTF-8")
  testthat::expect_equal(nrow(x),48L)
  testthat::expect_equal(anyDuplicated(x$variable),0L)
  testthat::expect_equal(rowSums(x[paste0("n_",1:5)]),x$n_valide)
  testthat::expect_equal(x$n_valide,unname(vapply(b[x$variable],function(v)sum(!is.na(v)),integer(1))))
  testthat::expect_true(all(x$moyenne>=1 & x$moyenne<=5 & x$variance>0))
  testthat::expect_equal(rowSums(x[paste0("proportion_",1:5)]),rep(1,48),tolerance=1e-8)
})

testthat::test_that("la sensibilité reproduit la référence et trace les sélections", {
  s <- read.csv("../../outputs/tables/sensibilite_psychometrie.csv")
  a <- read.csv("../../outputs/tables/alpha_cronbach.csv")
  o <- read.csv("../../outputs/tables/omega_mcdonald.csv")
  b <- readRDS("../../data/processed/questionnaire_clean.rds")
  testthat::expect_equal(nrow(s),32L)
  ref <- s[s$scenario=="TOUS",]
  testthat::expect_equal(ref$alpha,a$alpha_brut[match(ref$dimension,a$dimension)],tolerance=1e-8)
  testthat::expect_equal(ref$omega,o$omega_total_ordinal[match(ref$dimension,o$dimension)],tolerance=1e-8)
  testthat::expect_true(all(s$n_complets>0 & s$n_complets<=s$n_retenus))
  testthat::expect_equal(s$n_retenus+s$n_exclus,rep(nrow(b),nrow(s)))
  testthat::expect_true(all(is.finite(s$alpha) & is.finite(s$omega)))
  testthat::expect_true(all(abs(s$congruence_charges)<=1+1e-8))
  testthat::expect_equal(unique(s$n_exclus[s$scenario=="SANS_STRAIGHTLINING"]),sum(b$flag_straightlining,na.rm=TRUE))
  d <- read.csv("../../outputs/tables/decision_items.csv",fileEncoding="UTF-8")
  testthat::expect_equal(nrow(d),48L)
  testthat::expect_equal(anyDuplicated(d$variable),0L)
  testthat::expect_true(all(d$decision %in% c("CONSERVER","CONSERVER_AVEC_RESERVE","EXCLURE_SCORE","EXCLURE_ANALYSE")))
  testthat::expect_true(all(nchar(d$justification)>0))
  ancien <- read.csv("../../outputs/tables/item_total_analysis.csv",fileEncoding="UTF-8")
  testthat::expect_equal(d$item_total,ancien$item_total_corrige[match(d$variable,ancien$variable)])
  testthat::expect_equal(d$loading,ancien$charge[match(d$variable,ancien$variable)])
  testthat::expect_true(all(s$correlation_min>=-1 & s$correlation_max<=1))
  testthat::expect_true(all(s$RMSR>=0 & s$congruence_charges>=0))
  liste <- yaml::read_yaml("../../metadata/items_retenus_scores.yml")$items
  testthat::expect_setequal(unlist(liste),d$variable[d$decision %in% c("CONSERVER","CONSERVER_AVEC_RESERVE")])
})

testthat::test_that("les matrices et modèles psychométriques sont admissibles et traçables", {
  dims <- c("EXP","DIF","EVA","GCL","COL","NUM","DEV","REL")
  for(d in c(dims,"global")) {
    r <- readRDS(paste0("../../outputs/models/correlations_polychoric_",d,".rds"))
    testthat::expect_equal(nrow(r),if(d=="global")48L else 6L)
    testthat::expect_equal(r,t(r))
    testthat::expect_true(min(eigen(r,symmetric=TRUE)$values)>0)
    testthat::expect_true(all(abs(r)<=1+1e-8))
  }
  a <- read.csv("../../outputs/tables/alpha_cronbach.csv")
  o <- read.csv("../../outputs/tables/omega_mcdonald.csv")
  testthat::expect_equal(nrow(a),8L)
  testthat::expect_true(all(is.finite(a$alpha_brut) & a$alpha_brut<=1))
  testthat::expect_true(all(o$omega_total_ordinal[o$modele_admissible]>=0 & o$omega_total_ordinal[o$modele_admissible]<=1))
  it <- read.csv("../../outputs/tables/item_total_analysis.csv")
  testthat::expect_equal(nrow(it),48L)
  testthat::expect_true(all(it$decision_preliminaire %in% c("CONSERVER","A_EXAMINER")))
  p <- read.csv("../../outputs/tables/nombre_facteurs_parallel.csv")
  testthat::expect_equal(nrow(p),8L)
  testthat::expect_true(all(p$facteurs_suggeres>=0 & p$facteurs_suggeres<=6))
  testthat::expect_true(all(file.exists(paste0("../../outputs/figures/parallel_",dims,".png"))))
})
