source("../../R/functions/imperfections.R", encoding = "UTF-8", local = TRUE)
imp_config <- yaml::read_yaml("../../config/config.yml")$imperfections
imp_base <- readRDS("../../data/simulated/reponses_questionnaire.rds")
imp_ordre <- read.csv("../../questionnaire/ordre_passation.csv", fileEncoding = "UTF-8")
testthat::test_that("l'injection est reproductible, traçable et conserve les poids", {
  z <- introduire_imperfections(imp_base, imp_ordre, imp_config)
  testthat::expect_identical(z, introduire_imperfections(imp_base, imp_ordre, imp_config))
  testthat::expect_identical(z$donnees$id_enseignant, imp_base$id_enseignant)
  testthat::expect_identical(z$donnees$poids_base, imp_base$poids_base)
  testthat::expect_equal(sum(is.na(z$donnees[imp_ordre$variable])), sum(is.na(z$registre$apres)))
  testthat::expect_equal(sum(z$donnees$flag_rapide_simule), imp_config$nombre_rapides)
  testthat::expect_equal(sum(z$donnees$flag_straightlining_simule), imp_config$nombre_straightlining)
  testthat::expect_equal(sum(z$donnees$statut_questionnaire == "Abandon"), imp_config$nombre_abandons)
  testthat::expect_false(any(grepl("^(SCORE_PROV_|GAP_)|_reverse$", names(z$donnees))))
  testthat::expect_equal(z$donnees$taux_completion, rowMeans(!is.na(z$donnees[imp_ordre$variable])))
  testthat::expect_true(all(z$registre$variable[z$registre$cause == "manquant_fin"] %in% tail(imp_ordre$variable, imp_config$nombre_items_fin)))
  abandons <- unique(z$registre$id_enseignant[z$registre$cause == "abandon"])
  testthat::expect_true(all(is.na(z$donnees$CTRL04[match(abandons, z$donnees$id_enseignant)])))
})
